cmake_minimum_required(VERSION 3.10)

# Find required packages
find_package(Threads REQUIRED)

# Function to create example executables
function(add_example name source)
    add_executable(${name} ${source})
    target_link_libraries(${name}
        xtils
        xtils-autogen
        Threads::Threads
    )
    # Set output directory
    set_target_properties(${name} PROPERTIES
        RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/examples
    )
    set_target_properties(examples PROPERTIES DEPENDS ${name})
endfunction()
add_custom_target(examples)

# Add all example executables
add_example(basic_app basic_app.cc)
add_example(fsm_example fsm_example.cc)
add_example(inspect_example inspect_example.cc)
add_example(logger_example logger_example.cc)
add_example(tcp_example tcp_example.cc)
add_example(timer_example timer_example.cc)
add_example(udp_example udp_example.cc)
add_example(udp_multicast_example udp_multicast_example.cc)
add_example(cron_scheduler_example cron_scheduler_example.cc)
add_example(websocket_client websocket_client_example.cc)
add_example(common common.cc)
add_example(http_client http_client_example.cc)
add_example(http_client_advanced http_client_advanced_example.cc)
add_example(http_server http_server_example.cc)
add_example(http_router_advanced http_router_advanced_example.cc)
add_example(ipc_channel ipc_channel_example.cc)
add_example(websocket_server websocket_server_example.cc)
add_example(bt_example bt_example.cc)

add_custom_command(TARGET bt_example POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_directory
        ${CMAKE_CURRENT_SOURCE_DIR}/bt_trees
        ${CMAKE_BINARY_DIR}/examples/bt_trees
)

if(SCRIPTING_ENABLE)
  add_example(scripting_example scripting_example.cc)
  add_example(scripting_bench scripting_bench.cc)
  add_example(scripting_compare scripting_compare.cc)
endif()
