# Derive version from git tags.
# Produces: XTILS_VERSION_MAJOR, XTILS_VERSION_MINOR, XTILS_VERSION_PATCH,
#           XTILS_VERSION_STRING (e.g. "1.2.3"), XTILS_VERSION_FULL (e.g. "1.2.3-4-gabcdef")

find_package(Git QUIET)

if(GIT_FOUND AND EXISTS "${CMAKE_SOURCE_DIR}/.git")
  execute_process(
    COMMAND ${GIT_EXECUTABLE} describe --tags --always --match "v[0-9]*"
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_DESCRIBE
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE GIT_DESCRIBE_RESULT
  )
else()
  set(GIT_DESCRIBE_RESULT 1)
endif()

if(GIT_DESCRIBE_RESULT EQUAL 0 AND GIT_DESCRIBE MATCHES "^v([0-9]+)\\.([0-9]+)\\.([0-9]+)(.*)")
  set(XTILS_VERSION_MAJOR ${CMAKE_MATCH_1})
  set(XTILS_VERSION_MINOR ${CMAKE_MATCH_2})
  set(XTILS_VERSION_PATCH ${CMAKE_MATCH_3})
  set(XTILS_VERSION_SUFFIX "${CMAKE_MATCH_4}")  # e.g. "-4-gabcdef"
else()
  # Fallback when not in a git repo or no tags
  set(XTILS_VERSION_MAJOR 0)
  set(XTILS_VERSION_MINOR 0)
  set(XTILS_VERSION_PATCH 0)
  set(XTILS_VERSION_SUFFIX "-unknown")
endif()

set(XTILS_VERSION_STRING "${XTILS_VERSION_MAJOR}.${XTILS_VERSION_MINOR}.${XTILS_VERSION_PATCH}")
set(XTILS_VERSION_FULL "${XTILS_VERSION_STRING}${XTILS_VERSION_SUFFIX}")

message(STATUS "xtils version: ${XTILS_VERSION_FULL}")
