include(${CMAKE_CURRENT_LIST_DIR}/version.cmake)

file(MAKE_DIRECTORY ${CMAKE_BINARY_DIR}/generated)
set(XTILS_AUTOGEN_FILE xtils-autogen.c)
set(XTILS_AUTOGENED ${CMAKE_BINARY_DIR}/generated/${XTILS_AUTOGEN_FILE})

set(XTILS_AUTOGEN_CONTENT [[
// auto generated by xtils-autogen.cmake
const char* XTILS_BUILD_TIME = __DATE__ " " __TIME__;
const unsigned int XTILS_VER_MAJOR = @XTILS_VERSION_MAJOR@;
const unsigned int XTILS_VER_MINOR = @XTILS_VERSION_MINOR@;
const unsigned int XTILS_VER_PATCH = @XTILS_VERSION_PATCH@;
const char* XTILS_VER_STRING = "@XTILS_VERSION_FULL@";
]])

file(WRITE ${XTILS_AUTOGENED}.in "${XTILS_AUTOGEN_CONTENT}")
configure_file(${XTILS_AUTOGENED}.in ${XTILS_AUTOGENED} @ONLY)

add_custom_command(
    OUTPUT ${XTILS_AUTOGENED}.generated
    COMMAND ${CMAKE_COMMAND} -E touch ${XTILS_AUTOGENED}
    COMMENT "Flashing ${XTILS_AUTOGEN_FILE}"
    DEPENDS ${XTILS_AUTOGENED}
    VERBATIM
)
add_library(xtils-autogen STATIC ${XTILS_AUTOGENED})

add_custom_target(generate_xtils_autogen ALL DEPENDS ${XTILS_AUTOGENED}.generated)
include_directories(${CMAKE_BINARY_DIR}/generated)
